In [1]:
import numpy as np

In [7]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr

array([[47, 13, 71, 52, 34],
       [ 9, 63, 82, 65, 38],
       [77, 31,  5, 12, 61],
       [43, 68, 92, 48, 23]])

In [8]:
# Indexing using boolean arrays / Filtering
arr[arr > 50]

array([71, 52, 63, 82, 65, 77, 61, 68, 92])

In [10]:
arr[(arr > 50) & (arr % 2 != 0)] # fitting conditions into numpy array

array([71, 63, 65, 77, 61])

In [13]:
arr[(arr > 20) & (arr % 3 == 0)] = 0
arr

array([[47, 13, 71, 52, 34],
       [ 9,  0, 82, 65, 38],
       [77, 31,  5, 12, 61],
       [43, 68, 92,  0, 23]])