In [1]:
import numpy as np

In [4]:
arr1 = np.arange(24).reshape(6,4)

In [5]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
arr1[[0,2,4]] # Fethcing 1,3,5 rows

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [35]:
arr1[:,[0, -1]] # Fetching 1st and last columns 

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19],
       [20, 23]])

In [42]:
arr2 = np.arange(1,15).reshape(7,2)
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [54]:
arr2[:,[1]]

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14]])