### #.Different ways to reshape an Numpy Array

    1. Ravel
    2. Reshape
    3. Transpose
    4. Stacking
    5. Splitting

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6,12)

In [3]:
arr1 = arr1.reshape(3,2)

In [4]:
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
arr1.ndim

2

In [12]:
arr1.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [14]:
arr1.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [15]:
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
arr2 = np.arange(12,18).reshape(3,2)
arr2

array([[12, 13],
       [14, 15],
       [16, 17]])

In [21]:
np.hstack((arr1, arr2)) # Stacking 2 nd-arrays, Horizontaly

array([[ 6,  7, 12, 13],
       [ 8,  9, 14, 15],
       [10, 11, 16, 17]])

In [29]:
np.vstack((arr1, arr2)) # Stacking 2 nd-arrays, Verticaly

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [30]:
arr3 = np.arange(18, 24).reshape(3,2)

In [31]:
arr3

array([[18, 19],
       [20, 21],
       [22, 23]])

In [38]:
# Horizontaly stacking 3 numpy arrays
np.hstack((arr1, arr2, arr3))

array([[ 6,  7, 12, 13, 18, 19],
       [ 8,  9, 14, 15, 20, 21],
       [10, 11, 16, 17, 22, 23]])

In [39]:
# Verticaly stacking 3 numpy arrays
np.vstack((arr1, arr2, arr3))

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [55]:
np.hsplit(arr1,2)

[array([[ 6],
        [ 8],
        [10]]),
 array([[ 7],
        [ 9],
        [11]])]

In [56]:
np.vsplit(arr2,3)

[array([[12, 13]]), array([[14, 15]]), array([[16, 17]])]