In [3]:
import numpy as np

In [4]:
np_arr1 = np.arange(24)
np_arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
# Reshaping the arr
np_arr1 = np_arr1.reshape(6,4)

In [6]:
np_arr2 = np.arange(1, 6)
np_arr2

array([1, 2, 3, 4, 5])

### #.Indexing, Extracting single item from matrix

In [7]:
np_arr2[3]

4

In [8]:
np_arr2[1]

2

### #.Slicing, Extracting multiple items from matrix

In [9]:
np_arr2[1:4]

array([2, 3, 4])

In [10]:
np_arr2[2:4]

array([3, 4])

In [11]:
np_arr2[-1]

5

In [12]:
np_arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
np_arr1[2]

array([ 8,  9, 10, 11])

In [14]:
np_arr1[:,2] # 3rd column

array([ 2,  6, 10, 14, 18, 22])

In [15]:
np_arr1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [16]:
np_arr1[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [17]:
np_arr1[4:5, 1:3]

array([[17, 18]])

In [18]:
np_arr1[4:, 2:]

array([[18, 19],
       [22, 23]])

### #.Iteration

In [19]:
# Iterating over rows
for i in np_arr1: 
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [20]:
# Iterating over every items
for i in np.nditer(np_arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [21]:
new_arr = np_arr1.reshape(4,6)
new_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [22]:
new_arr[:,3:4] # Extract 4th column

array([[ 3],
       [ 9],
       [15],
       [21]])

In [23]:
new_arr[:,2:4] # Extract 3rd and 4th column

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

In [29]:
!conda update conda

/bin/bash: line 1: conda: command not found
