In [14]:
import numpy as np

In [28]:
np.random.random()

0.5988358917065396

In [89]:
np.random.seed(2) # seed function generates same random number again and again
np.random.random()

0.43599490214200376

In [135]:
np.random.uniform(1,11)

5.36747263026799

In [142]:
np.random.uniform(1, 11, size=30).reshape(5,6)

array([[10.83138361,  7.52906951,  5.77736353,  1.87787555,  6.58950795,
         2.81150229],
       [ 6.1440206 ,  7.08930149,  9.3321249 ,  4.23750582, 10.88862093,
        10.9495026 ],
       [ 9.26150819,  7.94152545,  8.33669798,  9.7526881 , 10.51510148,
         9.52262927],
       [ 7.4093864 ,  1.73498385,  7.23384714,  4.53213892,  2.64778623,
         9.93166187],
       [ 9.24890481,  6.26638424,  5.63449256,  5.89301288,  3.6072002 ,
         5.02637923]])

In [159]:
np.random.randint(1, 11)

9

In [174]:
np.random.randint(1, 11, size=20)

array([ 9,  7,  9,  7,  5,  4,  3,  8,  5,  4, 10,  1,  3,  4,  1,  2,  2,
       10,  7,  3])

In [180]:
np.random.randint(1, 11, size=20).reshape(5,4)

array([[3, 6, 2, 8],
       [2, 5, 9, 1],
       [4, 6, 6, 1],
       [4, 1, 3, 3],
       [3, 1, 6, 2]])

In [192]:
num = np.random.randint(1, 11, size=6)
num

array([ 1,  8,  2, 10, 10,  6])

In [193]:
num * 2

array([ 2, 16,  4, 20, 20, 12])

In [194]:
np.max(num)

10

In [195]:
np.min(num)

1

In [203]:
np.argmax(num)

3

In [209]:
num[np.argmax(num)] # Returns index of maximun number from the array

10

In [216]:
num[np.argmin(num)] # Returns index of minium number from the array

1

In [224]:
num % 2 != 0 # Condition to check for odd num

array([ True, False, False, False, False, False])

In [225]:
num[num % 2 != 0] # Fitting the given condition inside the array

array([1])

In [226]:
num % 5 == 0 # Condition to check number is divisible by 5

array([False, False, False,  True,  True, False])

In [227]:
num[num % 5 == 0] # Fitting given condition inside the array

array([10, 10])

In [231]:
# If the number is Even , change the number to 2 else return number as it is
num % 2 == 0 # given condition

array([False,  True,  True,  True,  True,  True])

In [237]:
# Fitting the given condition inside the array
num[num % 2 == 0] = 2
num

array([1, 2, 2, 2, 2, 2])

In [239]:
num

array([1, 2, 2, 2, 2, 2])

In [244]:
# Performing the same operation using np.where func()
new_num = np.random.randint(1, 50, 6)
new_num

array([30,  5, 26, 37, 29, 40])

In [245]:
np.where(new_num % 2 != 0, 'Odd', new_num)

array(['30', 'Odd', '26', 'Odd', 'Odd', '40'], dtype='<U21')

In [247]:
new_num # This function does not change the original array, like in previous case

array([30,  5, 26, 37, 29, 40])

In [248]:
arr1 = np.random.randint(1, 50, size=20)

In [249]:
arr1

array([11, 45, 46, 38, 22, 24, 28, 45, 11,  3, 46, 35, 24,  8,  7, 29, 44,
       38, 37, 17])

In [252]:
sorted_arr1 = np.sort(arr1)
sorted_arr1

array([ 3,  7,  8, 11, 11, 17, 22, 24, 24, 28, 29, 35, 37, 38, 38, 44, 45,
       45, 46, 46])

In [257]:
np.percentile(sorted_arr1, 50)

28.5

In [258]:
np.percentile(sorted_arr1, 70)

38.0

In [260]:
np.percentile(sorted_arr1, 90)

45.1

In [261]:
np.percentile(sorted_arr1, 99)

46.0