### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(f'Current Numpy Version: {np.__version__}')
print(f'Numpy Configs: {np.show_config()}')

Current Numpy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: blas
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140228583157936
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -g, -O2, -fno-omit-frame-pointer, -mno-omit-leaf-frame-pointer, -ffile-prefix-map=/build/numpy-VpSPb5/numpy-1.26.4+ds=.,
      -flto=auto, -ffat-lto-objects, -fstack-protector-strong, -fstack-clash-protection,
      -Wformat, -Werror=format-security, -fcf-protection, -fdebug-prefix-map=/build/numpy-VpSPb5/numpy-1.26.4+ds=/usr/src/numpy-1:1.26.4+ds-6ubuntu1,
      -Wdate-time, -D_FORTIFY_SOURCE=3
    commands: cc
    linker: ld.bfd
    linker args: -Wl,-Bsymbolic-functions, -

### 3. Create a null vector of size 10 (★☆☆)


In [3]:
null_vector = np.zeros(10)
print(null_vector)
print(null_vector.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(f'Total memorey size of arr: {arr.itemsize * arr.size} Bytes')

Total memorey size of arr: 40 Bytes


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [7]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last) (★☆☆)


In [8]:
arr = np.arange(1, 11)
print(f'Original: {arr}')
arr_reversed = arr[::-1]
print(f'Reversed: {arr_reversed}')

Original: [ 1  2  3  4  5  6  7  8  9 10]
Reversed: [10  9  8  7  6  5  4  3  2  1]


### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [9]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) NOT SOLVED !


In [10]:
arr1 = np.array([1, 2, 0, 0, 4, 0])
np.where(arr1 > 0, arr1, None)

array([1, 2, None, None, 4, None], dtype=object)

In [11]:
# SOLUTION:
arr1 = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr1)

(array([0, 1, 4]),)

### 11. Create a 3x3 identity matrix (★☆☆)


In [12]:
indentity_matrix = np.identity(3)
print(indentity_matrix)
print(indentity_matrix.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)



### 12. Create a 3x3x3 array with random values (★☆☆)


In [13]:
np.random.randint(1,10,size=9).reshape(3,3) # Wrong Solution !!

array([[9, 5, 2],
       [8, 3, 3],
       [4, 4, 4]])

In [14]:
# Correct Solution: Create a 3x3x3 array with random values
np.random.random((3,3,3))

array([[[0.33103718, 0.44244192, 0.30182889],
        [0.86944322, 0.54004841, 0.45302578],
        [0.4915021 , 0.45534892, 0.42422367]],

       [[0.9690746 , 0.14296887, 0.45726123],
        [0.31226245, 0.59388571, 0.46170317],
        [0.94512218, 0.20660896, 0.89820578]],

       [[0.10020196, 0.69821697, 0.91150576],
        [0.54138753, 0.25515046, 0.05772049],
        [0.1271166 , 0.02418785, 0.32418174]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [15]:
arr2 = np.random.randint(1,101,size=100).reshape(10,10)
print(arr2)
print(arr2.shape)
print(arr2.min())
print(arr2.max())

[[ 96  53  58  97  74  90  54  94  98   4]
 [ 83  33  57  36  93  58  90  24  82  42]
 [ 14  14  38  60  30  45  83   7  99  36]
 [ 98   6  44 100  92  11   9  92  52  62]
 [ 82  76  68  37  81  85  71   2  75   2]
 [  1  22  92   4  25  20  14  59  83   8]
 [ 16  28  65   5  63  78   4  64  96  59]
 [ 85  79  97   1  91  54  86  64  56  86]
 [ 68  86  48  43  29  97  50  79   4  72]
 [ 76  80  92  76  42  58   8  88  89  93]]
(10, 10)
1
100


In [16]:
# Another Solution:
Z = np.random.random((10,10))
Zmin, Zmax = np.min(Z), np.max(Z)
print(Zmin, Zmax)

0.005579251481431791 0.980499437660527


### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [17]:
arr3 = np.random.randint(1,30, size=30) # Incorrect Solution
print(arr3)
print(arr.mean())
print(arr.size)

[16 24 20 28 18 16  2 25 26 25 17  9 13 14 27 14  8 14  9 26 20  2  5 12
  1  1 24 25 17  8]
5.5
10


In [18]:
# Correct Solution:
Z = np.random.random(size=30)
Zmean = Z.mean()
print(Z, Zmean, Z.size)

[0.70438667 0.89612874 0.37909227 0.22684821 0.69161936 0.8775257
 0.1605971  0.75642261 0.52321314 0.7074937  0.22995884 0.62761672
 0.06703335 0.22298528 0.49696418 0.85599273 0.56936681 0.60455664
 0.46540187 0.85029923 0.58179226 0.30590747 0.0801468  0.33585984
 0.76701274 0.22103655 0.66329215 0.55269726 0.10526814 0.41951648] 0.4982010956540206 30


### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) NOT SOLVED !


In [19]:
# arr4 = np.arange(1,21).reshape(5,4)
# arr4[arr4[1:4,1:3]] = 0 
# arr4 # This code is Incorrect, due to a sily mistake !

In [20]:
# Correct Solution:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) NOT SOLVED

In [21]:
Z = np.zeros((4,4))
Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# Correct Solution: 
# Solution:1 (By using np.pad())
# Z = np.ones((5,5))
# Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
# Z
# Soltuion:2 (By using fancy indexing)
Z = np.ones((5,5))
#Z[:,[0,-1]] = 0
Z[[0,-1],:] = 0
Z

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

### 17. What is the result of the following expression? (★☆☆) NOT UNDERSTOOD..

In [23]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
np.nan in set([np.nan])
0.3 == 3 * 0.1

nan
False
False
nan


False

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) NOT SOLVED !!


In [24]:
# Correct Solution:
Z = np.diag(1+np.arange(4), k=-1) # Not Understood !
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [25]:
Z = np.arange(1, 26).reshape(5,5)
Z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
Z = np.arange(4)
Z

array([0, 1, 2, 3])

### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) NOT SOLVED !!


In [27]:
# Correct Solution:
import numpy as np

def create_checkerboard(n):
    # Create an n x n checkerboard pattern matrix.
    checkerboard = np.zeros((n,n), dtype=int)
    
    for i in range(n): # This outer loop Iterate over Rows.
        for j in range(n): # This inner loop Iterate over columns.
            # A cell is 1 (black) is the sum of it's indices, else 0 (white).
            checkerboard[i,j] = (i+j) % 2
    return checkerboard

# Generate an 8x8 checkerboard matrix.
checkerboard_matrix = create_checkerboard(8)
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆) NOT SOLVED !!!


In [28]:
Z = np.ones((6,7,8))
np.unravel_index(99,(6,7,8)) # Not Understood !

(1, 5, 3)

### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) NOT SOLVED !

In [29]:
Z = np.tile(np.array([[1, 0], [0, 1]]),(4,4))

In [30]:
Z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 22. Normalize a 5x5 random matrix (★☆☆), Have no Idea how to solve !

In [31]:
# Correct Solution:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
Z

array([[ 0.20784131, -0.38775309, -0.05903842, -1.96320106,  0.53410875],
       [ 1.37824318,  0.08182256, -0.34148872, -0.5821434 ,  1.8476154 ],
       [ 0.59382871, -1.51756778,  1.35894138, -1.31710281, -0.46507912],
       [-1.60364888,  0.13407875,  0.26519301,  0.03714799,  1.2024745 ],
       [ 0.8095318 ,  0.76350578, -1.07867211, -0.92921656,  1.03057882]])

### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) Not Understood at all...

In [32]:
gba_dtype = np.dtype([('R', np.uint8),   # Red channel
                       ('G', np.uint8),   # Green channel
                       ('B', np.uint8),   # Blue channel
                       ('A', np.uint8)])  # Alpha channel

In [33]:
gba_dtype

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) Encountered Error !


In [34]:
a = np.arange(1, 16).reshape(5,3)
b = np.arange(1, 7).reshape(3,2)
print(a)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]


In [35]:
res = np.dot(a, b)
res

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆), NOT SOLVED


In [36]:
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] = -1
Z

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10])

In [37]:
a = [1, 2, 3, 4, 5]
a.append(34)
a.pop()
sum(a)

15

### 26. What is the output of the following script? (★☆☆)


In [38]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆) No idea !

In [39]:
Z = 1 + np.arange(5)
Z

array([1, 2, 3, 4, 5])

In [40]:
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z) # Illegal Expression
print(1j * Z)
print(Z/1/1)
# print(Z<Z>Z) # Illegal Expression

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]


### 28. What are the result of the following expressions? (★☆☆) No idea !


In [41]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_5115/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_5115/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_5115/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 29. How to round away from zero a float array ? (★☆☆) No idea !


In [42]:
Z = np.random.uniform(-10,10,10)
print(f'Original Values: {Z}') 
print(f'Round Values: {np.copysign(np.ceil(np.abs(Z)),Z)}')

Original Values: [-8.84227444  0.18628599 -4.89772605 -4.8617882   3.57180637  0.56031895
  4.13544242  4.59518316 -4.70500526  8.53538364]
Round Values: [-9.  1. -5. -5.  4.  1.  5.  5. -5.  9.]


### 30. How to find common values between two arrays? (★☆☆)  Not Solved !


In [43]:
a, b = np.random.randint(0, 10, size=10), np.random.randint(0, 10, size=10)
a = a.reshape(2,5)

In [44]:
print(np.intersect1d(a,b))

[0 1 2 5 7 8 9]


### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [45]:
import warnings
warnings.filterwarnings('ignore')

### 32. Is the following expressions true? (★☆☆)


In [46]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) Not Solved !


In [47]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tommorow = np.datetime64('today') + np.timedelta64(1)

In [48]:
yesterday, today, tommorow

(numpy.datetime64('2024-06-12'),
 numpy.datetime64('2024-06-13'),
 numpy.datetime64('2024-06-14'))

### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) No Idea !


In [49]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [50]:
a, b = np.random.random(20), np.random.random(20)

In [51]:
res = ((a+b)*(-a/2))

In [52]:
res # Incorrect Solution !

array([-0.45816009, -0.46099149, -0.30825701, -0.54832105, -0.20157495,
       -0.2034395 , -0.00564365, -0.47912674, -0.1519036 , -0.11062155,
       -0.33922444, -0.50939524, -0.13246275, -0.18508188, -0.00079414,
       -0.24929826, -0.45209381, -0.08790825, -0.11507146, -0.21294534])

In [53]:
# Correct Solution:
A, B = np.ones(3)*1, np.ones(3)*2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆) No Idea !


In [54]:
Z = np.random.uniform(0,10,size=10)
print(f'Before Extraction: {Z}')
print('After Extraction:')
print(Z-Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

Before Extraction: [7.53458173 2.26246156 3.78778766 2.80921997 7.31965667 0.31635752
 1.09460238 9.00025092 1.32902714 9.51669066]
After Extraction:
[7. 2. 3. 2. 7. 0. 1. 9. 1. 9.]
[7. 2. 3. 2. 7. 0. 1. 9. 1. 9.]
[7. 2. 3. 2. 7. 0. 1. 9. 1. 9.]
[7 2 3 2 7 0 1 9 1 9]
[7. 2. 3. 2. 7. 0. 1. 9. 1. 9.]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [55]:
Z = np.ones((5,5))
Z[:,:] = np.arange(0,5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [56]:
# Second Solution:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])


### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [57]:
Z = np.random.randint(0, 11, size=10)
Z = Z.reshape(2,5)
Z # Incorrect Solution !

array([[ 2, 10,  1,  7,  0],
       [ 3,  5,  6,  9,  4]])

In [58]:
# Correct Solution:
def generator():
    for i in range(10):
        yield i
Z = np.fromiter(generator(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [59]:
Z = np.random.random(size=10)
Z # Incorrect Solution !

array([0.06952776, 0.84205411, 0.90411   , 0.20191042, 0.02133085,
       0.46266377, 0.26214299, 0.68020669, 0.02224026, 0.57014864])

In [60]:
# Correct Solution:
Z = np.linspace(0,1,num=11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### 40. Create a random vector of size 10 and sort it (★★☆)


In [61]:
Z = random.random(10)
print(f'Before Sort: {Z}')
Z.sort()
print()
print(f'After Sort: {Z}')

Before Sort: [0.39952128 0.72457586 0.26748138 0.98896784 0.34840135 0.08552631
 0.20428907 0.97722088 0.22661435 0.43040694]

After Sort: [0.08552631 0.20428907 0.22661435 0.26748138 0.34840135 0.39952128
 0.43040694 0.72457586 0.97722088 0.98896784]



### 41. How to sum a small array faster than np.sum? (★★☆) No Idea !


In [62]:
a = np.arange(10).reshape(5,2)
res = np.sum(a)
res # Incorrect Solution ! (same output..)

45

In [63]:
# Correct Solution:
Z = np.arange(10)
np.add.reduce(Z)

45

### 42. Consider two random array A and B, check if they are equal (★★☆) No Idea ! 


In [64]:
a = np.random.randint(0,20,size=10)
b = np.random.randint(0,20,size=10)
print(a,b[a == b]) # Incorrect Solution !

[ 3  1  8  9 14  4 16  8 12  3] []


In [65]:
# Correct Solution
A, B = np.random.randint(0,2,size=5), np.random.randint(0,2,size=5)
# Assuming identical shapes of the arrays
equals = np.allclose(A,B)
print(equals)

False


### 43. Make an array immutable (read-only) (★★☆) Not Solved !

In [66]:
# Solution:
Z = np.ones((3,3))
Z.flags.writeable = False
Z[:,-1] = 4
Z # not Z has became immutable !

ValueError: assignment destination is read-only

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) No Idea !

In [ ]:
Z = random.random((10,2))
Z

In [ ]:
X, Y = Z[:,[0]], Z[:,[1]]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print()
print(T)

### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [ ]:
Z = np.arange(0,11)
Z[np.max(Z)] = 0
Z # Incorrect Solution !

In [ ]:
# Correct Solution:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆) No Idea, how to solve !

In [ ]:
# Solution
Z = np.zeros((5,5),[('x',float), ('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,num=5), np.linspace(0,1,num=5))
Z

### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆) No Idea, how to solve !


In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))


### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [ ]:
# Solution:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


### 49. How to print all the values of an array? (★★☆)


In [ ]:
# # Solution:
np.set_printoptions(threshold=float('inf'))
Z = np.zeros((40,40))
print(Z)

### 50. How to find the closest value (to a given scalar) in a vector? (★★☆), Don't know how to solve!


In [ ]:
Z = np.arange(100)
V = np.random.uniform(0,100)
index = (np.abs(Z-V)).argmin()
print(Z[index])

### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆), Don't know how to solve!


In [ ]:
Z = np.zeros(10, [('position', [('x',float,1),
                                ('y', float,1)]),
                  ('color', [('r',float,1),
                             ('g',float,1),
                             ('b',float,1)])])
Z

### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [ ]:
Z = np.ones((2,2))
Z.dtype
Z = Z.astype('int32')
Z # Incorrect Solution

In [ ]:
# Correct Solution:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

### 54. How to read the following file? (★★☆)


In [ ]:
import os

file = open('test.txt', 'a')
file.write('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')
file.close() # Incorrect Soltuion

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=',', dtype=np.int16)
print(Z)

### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)
print()
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

### 56. Generate a generic 2D Gaussian-like array (★★☆)


In [ ]:
# Solution:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G) # Not Understood the mathematical formulations

### 57. How to randomly place p elements in a 2D array? (★★☆)


In [ ]:
# Solution:
n, p = 10, 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z) # Not understood the mathematical formulations

### 58. Subtract the mean of each row of a matrix (★★☆) NOT SOLVED !


In [ ]:
Z = np.arange(1, 26).reshape(5,5)
for i in range(len(Z)):
    res = Z[0] - np.mean(Z[0])
    Z[0] += 1 
print(res) # Incorrect Solution

In [ ]:
# Correct Solution:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1, keepdims=True)
Y

### 59. How to sort an array by the nth column? (★★☆)


In [ ]:
Z = np.random.randint(1, 20, 25).reshape(5,5)
res = np.sort(Z)
res # Incorrect Solution !

In [ ]:
# Correct Solution:
Z = np.random.randint(0,10,(3,3))
print(Z)
print()
print(Z[Z[:,-1].argsort()])


### 60. How to tell if a given 2D array has null columns? (★★☆)


In [ ]:
# Solution:
# Z = np.random.randint(0,3,(3,10))
# print((~Z.any(axis=0)).any())
Z = np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

### 61. Find the nearest value from a given value in an array (★★☆)


In [ ]:
Z = np.random.uniform(0,1,size=10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [ ]:
Z = np.arange(1,4)
Z1 = np.arange(4,7).reshape(3,1)
res = np.sum(Z) + np.sum(Z1) # Incorrect Solution !

In [ ]:
# Correct Solution:
A, B = np.arange(3).reshape(3,1), np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y
print(it.operands[2])

In [ ]:
# Another Example:
X = np.arange(25).reshape(25,1)
Y = np.arange(25).reshape(1,25)

In [ ]:
iterate = np.nditer([X,Y,None])
for x,y,z in iterate:
    z[...] = x + y
print(iterate.operands[2])

### 63. Create an array class that has a name attribute (★★☆)


In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', 'no name')

Z = NamedArray(np.arange(10), 'range_10')
print(Z)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', 'no name')
        
Z = NamedArray(np.arange(20), 'range_20')
print(Z)


### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [ ]:
# Solution:
Z = np.ones(10)
I = random.randint(0, len(Z), size=20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

In [ ]:
# Another solution:
Z = np.ones(10)
I = np.random.randint(0,len(Z),size=20)
np.add.at(Z, I, 1)
print(Z)

### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.arange(1,7)
I = np.random.randint(1,10,size=len(X))
F = np.bincount(I,X)
print(F)

### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [ ]:
# 1st Solution:
w, h = 256, 256
I = np.random.randint(0, 4, (w, h, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

In [ ]:
# 2nd Solution: Faster Version !
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32), [1, 256, 65536])
n = len(np.unique(I24))
print(n)

### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) Not Solved !


In [ ]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
#print(A)
print()
#print(A[-2])
print()
sum = A.sum(axis=(-2, -1))
print(sum)

In [ ]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)


In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


### 69. How to get the diagonal of a dot product? (★★★)


In [ ]:
# Solution:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.dot(A, B))
print(np.diag(np.dot(A, B)))

In [ ]:
# Faster version !
np.sum(A * B.T, axis=1)ss

### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [ ]:
# My solution 
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([])
for i in range(0,len(arr2),2):
    arr2 = np.append(arr2, i)
arr2 # Incorrect Solution !

In [ ]:
# Correct Solution:
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1) * nz)
Z0[::nz+1] = Z
print(Z0)

### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

### 72. How to swap two rows of an array? (★★★)


In [ ]:
A = np.arange(25).reshape(5,5)
print(A)

In [ ]:
A[[0,1]] = A[[1,0]]
print(A)

### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)


In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0',F.dtype), ('p1',F.dtype)])
G = np.unique(G)
print(G)

### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [ ]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)),C)
A

### 75. How to compute averages using a sliding window over an array? (★★★)


In [ ]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), n=3))

In [79]:
# Another Solution:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [80]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]



### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [81]:
Z = np.random.randint(0,2,size=100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0, 1.0, size=100)
print(Z)
print(np.negative(Z, out=Z))

[ 0.21910126  0.68688632 -0.31263723  0.67315105  0.69789668 -0.00946461
 -0.7510623   0.64405668  0.68312904  0.99301734  0.67389755  0.10213549
  0.05918168  0.90490214  0.09150666  0.38181517 -0.89727908 -0.27714757
  0.60226388  0.93081035  0.27475098  0.08608743 -0.8166326   0.55907002
  0.97718053  0.09512711  0.29404503  0.61513833  0.57614402  0.20165361
  0.8808311  -0.6082798  -0.92823157 -0.18001436  0.7295688   0.60628294
 -0.18294249 -0.97164301 -0.19808441  0.82186075  0.2000925   0.59990456
  0.09674854  0.36104201 -0.39615403 -0.30790112 -0.2699847  -0.75195149
 -0.4470001   0.46701588  0.32856467  0.22860272  0.94547292  0.22337566
 -0.35368969  0.61828858  0.56237489  0.00607401  0.17116421  0.08813692
 -0.49486023  0.79091428 -0.35900666 -0.67780042 -0.93864128  0.99451857
 -0.25336247  0.77340937  0.12508981  0.50292755 -0.97628473 -0.91163507
  0.34275949 -0.29909593  0.83727247 -0.25557694  0.25150284 -0.39061422
 -0.13458711  0.3971663   0.91239386  0.81680222 -0

### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


### Skip ! to much complicated syntax


### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [ ]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))

# print(P0)
# print()
# print(P1)
# print() 
# print(p) # Skip this as well !!

### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)


In [82]:
Z = np.random.randint(0, 10, (10,10))
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = P-Rs // 2
Z_stop = P+Rs // 2 + Rs%2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.minimum(Z_start, 0)).tolist()
R_stop = np.minimum(R_start, (R_stop - np.minimum(Z_stop - Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[tuple(r)] = Z[tuple(z)]

print(Z)
print(R)

[[0 8 7 5 9 4 1 5 0 3]
 [4 7 9 6 1 3 6 3 8 6]
 [0 0 7 3 2 2 1 8 6 8]
 [8 7 1 2 1 8 7 8 3 6]
 [7 7 2 9 9 1 4 1 9 7]
 [5 5 5 3 5 6 2 5 7 3]
 [8 3 2 2 1 2 4 9 0 7]
 [5 4 4 6 6 7 9 9 9 1]
 [0 2 7 1 6 0 8 3 2 5]
 [6 5 3 2 6 0 3 4 7 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]



### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [83]:
# Solution:
from numpy.lib import stride_tricks

Z = np.arange(1, 15, dtype=np.uint32)
print(Z)
R = stride_tricks.as_strided(Z, (11,4), (4,4))
#print(R)

# Another Soltuion:
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82. Compute a matrix rank (★★★)


In [ ]:
# # Solution:
Z = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(Z) # Singular value decomposition
rank = np.sum(S > 1e-10)
# print(rank)

# Another solution:
rank = np.linalg.matrix_rank(Z)
print(rank)

### 83. How to find the most frequent value in an array?


In [71]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[7 1 1 1 2 6 5 8 7 4 7 2 3 4 0 2 6 2 5 3 6 7 2 2 8 0 7 2 3 6 5 5 2 9 7 6 1
 7 1 5 6 3 8 9 9 7 6 4 1 3]
2


### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [109]:
# Solution: 
Z = np.random.randint(0,5,(10,10))
#print(Z)
n = 3
i =  1 + (Z.shape[0] - 3)
j = 1 + (Z.shape[1] - 3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
#C

# Another solution:
Z = np.random.randint(0,5,(10,10))
#print(sliding_window_view(Z, window_shape=(3,3)))

### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [139]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  3 11 11  9]
 [ 3  3  6  9 12]
 [11  6  1 42  9]
 [11  9 42  7  5]
 [ 9 12  9  5  6]]



### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [146]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0,2], [0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]



### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


In [152]:
# Solution:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0,Z.shape[0],k), axis=0),
                                   (np.arange(0, Z.shape[1],k)), axis=1)
#print(S)
# Another solution:
windows = np.lib.stride_tricks.sliding_window_view(Z, (k,k))
S = windows[::k, ::k, ...].sum(axis=(-2,-1))
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### 88. How to implement the Game of Life using numpy arrays? (★★★)


In [157]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2] + Z[1:-1,2:] + Z[2:,0:-2] + 
         Z[2:,0:-2] + Z[2:,1:-1] + Z[2:,2:])
    # Apply rules:
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    Z = iterate(Z)
    #print(Z) # I don't understand this code, so do the code of it !

### 89. How to get the n largest values of an array (★★★)


In [191]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print(Z[np.argsort(Z)[-n:]])

# Fast
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]



### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


In [193]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:,n] = arrays[n][ix[:,n]]
    
    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### 91. How to create a record array from a regular array? (★★★)


In [200]:
Z = np.array([('Hello', 2.5, 3),('World', 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats='S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [210]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

271 ms ± 8.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
201 ms ± 4.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
202 ms ± 32.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


In [227]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = A[..., np.newaxis, np.newaxis] == B
rows = np.where(C.any((3,1)).all(1))[0]
rows

array([0, 3])

### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [261]:
# Solution:
Z = np.random.randint(0,5,(10,3))
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
#print(U)

# Another Solution:
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 0 0]
 [3 1 2]
 [0 1 3]
 [2 3 1]
 [4 0 1]
 [1 4 4]
 [2 2 4]
 [2 4 1]
 [1 3 0]]


### 95. Convert a vector of ints into a matrix binary representation (★★★)


In [262]:
# My solution
a = np.array([1, 2, 3, 4])
for i in a:
    res = np.array([np.binary_repr(i)])
    print(res) # Incorrect Solution !

['1']
['10']
['11']
['100']


In [303]:
# Correct Solution:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
# print(B[:,::-1])

# Another Solution:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=uint8)
print(I)
print(np.unpackbits(I[:,newaxis],axis=1))

[  0   1   2   3  15  16  32  64 128]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### 96. Given a two dimensional array, how to extract unique rows? (★★★)


In [355]:
# Solution:
Z = np.random.randint(0,2,(6,3))
T = ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
#print(uZ)

# Another Solution:
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [1 1 0]
 [1 1 1]]


### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [373]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->',A) # np.sum(A)
np.einsum('i,i->', A, B) # A * B
np.einsum('i,i',A, B) # np.inner(A, B)
np.einsum('i,j->ij', A, B) # np.outer(A,B)

array([[0.24203265, 0.140137  , 0.18668795, 0.15133118, 0.08898566,
        0.12982453, 0.13767568, 0.18347434, 0.25084511, 0.01370245],
       [0.37830984, 0.21904155, 0.29180314, 0.23653863, 0.1390893 ,
        0.20292262, 0.21519437, 0.2867801 , 0.39208418, 0.02141765],
       [0.66008023, 0.38218672, 0.50914214, 0.41271587, 0.24268493,
        0.35406218, 0.37547411, 0.50037788, 0.68411389, 0.03736982],
       [0.54669211, 0.31653495, 0.42168206, 0.34181982, 0.20099668,
        0.29324162, 0.31097542, 0.41442331, 0.56659728, 0.03095046],
       [0.37298369, 0.2159577 , 0.2876949 , 0.23320845, 0.13713109,
        0.2000657 , 0.21216469, 0.28274258, 0.3865641 , 0.02111612],
       [0.11834744, 0.06852322, 0.09128537, 0.07399687, 0.04351159,
        0.0634807 , 0.0673197 , 0.08971401, 0.1226565 , 0.00670013],
       [0.79556504, 0.46063248, 0.61364615, 0.49742789, 0.29249724,
        0.42673523, 0.45254207, 0.60308297, 0.82453173, 0.04504016],
       [0.45688257, 0.26453519, 0.3524089

### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [401]:
phi = np.arange(0,10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment length
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) # integrate path
r_int = np.linspace(0,r.max(), num=200)
x_int = np.interp(r_int, r, x) # integrate path
y_int = np.interp(r_int, r, y)

### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [409]:
X = np.array([
    [1.0, 0.0, 3.0, 8.0],
    [2.0, 0.0, 1.0, 1.0],
    [1.5, 2.5, 1.0, 0.0]
])

n = 4
M = np.logical_and.reduce(np.mod(X,1) == 0, axis=-1)
M &= (X.sum(axis=-1)== n)
print(X[M])

[[2. 0. 1. 1.]]


### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [423]:
X = np.random.rand(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[0.47028199 0.58127584]
